name: docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rustdoc:
    uses: ./.github/workflows/reusable-rust-validate.yml
    with:
      run_examples: false
